### ISSUE TITLE
Flash-Speicher und 'zyklisches' Schreiben

### ISSUE THREAD

**Issue by CarlosEllan** [Optic00/ha-akkusteuerung-sma#7]
So, hab jetzt auch mal die ersten Automationen und Helfer angelegt.
Funktioniert soweit auch mit einem Sunny Island 8.0.
Bei der Automation 'Akkusteuerung' sind mir noch 2 Tippfehler bei den Alias aufgefallen, die aber keine Auswirkung haben: 'Akku schnell Entaden' und der Alias 'Wenn Akku Automatik' gehört wohl vor Zeile 107.
Aber zum Issue: Gibt es inzwischen eine offizielle Aussage von SMA, ob die Register 40149 und 40151 problemlos auch mehrfach am Tag beschrieben werden können? Die Modbus Dokumentation ist da sehr vage und je nach genutztem Flash-Speicher kann das kritisch werden.
Auf jeden Fall schon mal Danke für die Scripte. Sobald ich sie für meine Hardware und Bedürfnisse angepasst habe, melde ich mich.

**Comment by Skybarks** [comment]
Es gibt für die SMA Produkte im jeweiligen Download - Bereich des Produkts Listen mit den entspr. Modbus Parametern:
https://www.sma.de/service/downloads
Beim meinen beiden STP 10 SE und STP 10 z.B. sind die Register 40149 und 40151 als WO Register genannt. 
Für den Sunny Island 8 gibt´s das sicher auch.
Probleme gibt es laut SMA nur beim zyklischen Beschreiben von RW Parametern (Quelle: Modbus Beschreibung SMA)
Ich gehe mal davon aus, dass ein WO Register also beliebig oft geschrieben werden kann, da der Vorgang nur in den Arbeitsspeicher, und nicht auf die Flash Karte schreiben sollte.
Dazu gabs im Photovoltaik-Forum auch mal ne Frage (#57):
https://www.photovoltaikforum.com/thread/206718-sma-stp10-0-3se-40-welcher-modbus-register-zum-laden-der-batterie/?pageNo=6

**Comment by CarlosEllan** [comment]
Ich versuche ja auch schon länger, an die Registerbeschreibung der SI 8.0H-11 zu kommen. Leider ist das im Archiv von SMA sehr dürftig beschrieben, und in dem Dokument kommen die 40149 und 40151 nicht vor. Nur in einer allgemeinen Modbus Doku, die im Iobroker-Forum verlinkt wurde, konnte ich diese finden.
Da die beiden Register auch beim SI 8.0H-11 read-only sind (zumindest kommt nicht der vorher reingeschriebene Wert zurück), gehe ich davon aus, daß diese nicht im Flash gehalten werden - also unkritisch.
Ich schau mir jetzt mal die opti-automatic Automation an, hab aber etwas andere Vorstellung, wie ich meinen Speicher mit Tibber optimieren werde. Hier stehen zwar 40kWh LFP rum, aber die neue WP zieht auch über 1,5kW fast durchgängig. Ab März langweilt sich der Speicher eh mehr, als daß er belastet wird. Aber mit Modul 3 nach §14A dann schon interessanter - angeblich arbeitet SMA ja an einer Lösung mit Lichtblick. Allerdings funktioniert schon das prognosebasierte Solarladen bei SMA eher unzuverlässig.

**Comment by Skybarks** [comment]
> Allerdings funktioniert schon das prognosebasierte Solarladen bei SMA eher unzuverlässig.

Oh ja, die Erfahrung habe ich auch gemacht :-)
Was bei mir jetzt gut klappt, ist eine Kombination aus der Optic00 Akkusteuerung, der SMA-SEMP Anbindung von littleyoda (zu finden hier: https://github.com/littleyoda/ha-sma-semp), und ein paar HA-Automatiken die ich darauf aufgesetzt habe. 
Seitdem regelt der HA meine beiden WR und die Batterie so exakt, dass ich manchmal selbst staune.

**Comment by CarlosEllan** [comment]
So, bin inzwischen auch so weit gekommen, das das script 'Akkusteuerung' funktioniert.
Hab allerdings in Zusammenhang mit evcc ein 'Feature' festgestellt:

Wenn man in evcc unter Konfiguration/Hausbatterie den Schalter

` Verhindere Entladung im Schnell-Modus und bei geplantem Laden.`

eingeschaltet hat, funktioniert 'Akku schnell Laden' + Fahrzeug laden über evcc nicht. Unabhängig von der Einstellung, wie das BEV geladen werden soll.
Wenn der Schalter eingeschaltet ist, und unter Akkusteuerung 'Akku schnell Laden' eingestellt ist oder man dies über eine Automation umstellt, wird die Hausakku-Ladung unterbrochen, sobald evvc eine Ladung des Auto startet (egal , ob automatisiert oder wenn man es manuell auswählt). Reihenfolge ist dabei egal. Ich denke, daß ivcc hier auch auf den Akku zugreift und sich das dann beißt. Ist für mich unkritisch, aber evtl. interessant, falls auch jemand beide Integrationen nutzt.

**Comment by alphabravocharly72** [comment]
@CarlosEllan 
Genau sowas suche ich schon länger. 
Meine Config ist Core1, 3x SI 4.4-12, 20kWh Bat, Data Manager M.
Möchte es auf mein System umschreiben. Wäre es möglich das du mir deine yaml zukommen lässt? 
Danke

**Comment by CarlosEllan** [comment]
Das ist ja nicht in nur einer yaml.
Ich nutze ja nur die sma-se-akku-steuerung.yaml mit den drei Modi Akku schnell Laden, Akku Pause und Akku Automatisch. Akku schnell Entladen funktioniert bei mir auch, hab ich aber noch keinen Einsatz für (evtl. später, wenn meine Einspeisung über Direktvermarktung laufen sollte).
Hier meine sma-se-akku-steuerung.yaml:

```
alias: Akkusteuerung
description: ""
triggers:
  - entity_id:
      - input_select.akkusteuerung_sma_wr
      - input_number.akkusteuerung_ladestaerke_soll
      - input_number.akkusteuerung_entladestaerke_soll
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 1
    trigger: state
  - minutes: /30
    enabled: true
    trigger: time_pattern
  - event: start
    trigger: homeassistant
conditions: []
actions:
  - alias: Wenn Akku schnell Laden ...
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku schnell Laden
    then:
      - data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 802
        action: modbus.write_register
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - data:
          hub: sma-sr_wr
          address: 40149
          slave: 3
          value:
            - 65535
            - >-
              {{ 65535 - states('input_number.akkusteuerung_ladestaerke_soll') |
              int * 0.3333 }}
        action: modbus.write_register
  - alias: Wenn Akku schnell Entladen ...
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku schnell Entladen
    then:
      - data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 802
        action: modbus.write_register
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - data:
          hub: sma-sr_wr
          address: 40149
          slave: 3
          value:
            - 0
            - >-
              {{ states('input_number.akkusteuerung_entladestaerke_soll') | int
              }}
        action: modbus.write_register
  - alias: Wenn Akku Pause ...
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku Pause
    then:
      - data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 802
        action: modbus.write_register
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - data:
          hub: sma-sr_wr
          address: 40149
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
  - alias: Wenn Auto Automatik
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku Automatisch
    then:
      - data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 803
        action: modbus.write_register
  - alias: Wenn Akku 0.2C Laden
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku 0.2C Laden
    then:
      - data:
          hub: sma-sr_wr
          address: 40151
          slave: 3
          value:
            - 0
            - 802
        action: modbus.write_register
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - data:
          hub: sma-sr_wr
          address: 40149
          slave: 3
          value:
            - 65535
            - >-
              {{ 65535 - states('input_number.akkusteuerung_02c_ladestaerke') |
              int }}
        action: modbus.write_register
mode: single
```
und der Code für die Stapelkarte

```
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Akkusteuerung SMA STP-SE
  - type: custom:mushroom-chips-card
    chips:
      - type: conditional
        conditions:
          - condition: numeric_state
            entity: sensor.sma_energy_meter_psupplycounter
            above: 0.001
        chip:
          type: template
          entity: sensor.sma_energy_meter_psupplycounter
          content: "{{( states(entity) | float / 1000) | round(2) }}  MW "
          icon: mdi:battery-minus
          icon_color: red
      - type: conditional
        conditions:
          - condition: numeric_state
            entity: sensor.sma_energy_meter_pconsumecounter
            above: 0.001
        chip:
          type: template
          entity: sensor.sma_energy_meter_pconsumecounter
          content: "{{( states(entity) | float / 1000) | round(2) }}  MW "
          icon: mdi:battery-positive
          icon_color: green
      - type: entity
        entity: sensor.sunny_island_state_of_charge
        icon_color: blue
      - type: template
        entity: sensor.sunny_island_chargecycles
        content: "{{ states(entity)}}"
        icon: mdi:counter
        icon_color: yellow
      - type: entity
        entity: sensor.sunny_island_batterietemperatur
        icon: mdi:battery-charging-wireless-outline
      - type: entity
        entity: sensor.sma_stp_se_temperatur
        icon: mdi:power-socket-it
  - type: custom:mushroom-select-card
    entity: input_select.akkusteuerung_sma_wr
    name: Akkusteuerung
    primary_info: name
    secondary_info: last-changed
  - type: tile
    entity: input_boolean.akku_opti_automatik
  - type: tile
    entity: input_boolean.akku_nach_preis_laden
  - type: tile
    entity: input_boolean.pv_module_nicht_verfugbar
    name: PV-Module NA (z.B. Schnee bedeckt)
  - type: entities
    entities:
      - entity: input_number.akkusteuerung_ladestaerke_soll
        name: "Laden "
      - entity: input_number.akkusteuerung_entladestaerke_soll
        name: Entladen
      - entity: input_number.akkusteuerung_ab_welchem_restertrag_vollladen
        name: Restladeschw.
      - entity: input_number.akkusteuerung_02c_ladestaerke
        name: Laden 0.2C
      - entity: input_number.akkusteuerung_wr_ac_ueberschuss_grenze
        name: WR AC-Grenze
      - entity: input_number.akkusteuerung_wr_70proz_ueberschuss_grenze
        name: 70% Grenze
  - type: horizontal-stack
    cards:
      - type: tile
        name: Entladen Watt
        entity: sensor.sma_energy_meter_psupplycounter
      - type: tile
        name: Laden Watt
        entity: sensor.sma_energy_meter_pconsumecounter
```
Meine configuration.yaml habe ich nicht geändert, da die Wechselrichter über eine separate modbus.yaml aus der configuration.yaml aufgerufen werden:

```
# Akku-Wechselrichter
- name: sma-sr_wr
  type: tcp  
  host: 192.168.2.182
  port: 502
  delay: 2
  message_wait_milliseconds: 60
  timeout: 5
  sensors:
  - name: "Sunny Island - State of Charge"
    unique_id: SiSoC
    data_type: uint32 #U32
    input_type: holding
    slave: 3
    address: 30845
    unit_of_measurement: "%"
  - name: "Sunny Island - Batterietemperatur"
    unique_id: SiBatTemp
    data_type: uint32 #U32
    input_type: holding
    slave: 3
    address: 30849
    unit_of_measurement: "°C"
    scale: 0.1
  - name: "Sunny Island - Batteriestrom"
    unique_id: SiBatCurrent
    data_type: int32 #S32
    input_type: holding
    slave: 3
    address: 30843
    precision: 0
    unit_of_measurement: "A"
  - name: "Sunny Island - Batteriespannung"
    unique_id: SiBatVolt
    data_type: uint32 #S32
    input_type: holding
    slave: 3
    address: 30851
    unit_of_measurement: "V"
    scale: 10
  - name: "Sunny Island - Entladegrenze"
    unique_id: SiDisLimit
    data_type: int32 #S32
    input_type: holding
    slave: 3
    address: 31009
    unit_of_measurement: "%"
  - name: "Sunny Island - Netzeinspeisezähler"
    unique_id: SiNetFeed
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 30583
    unit_of_measurement: "kWh"
  - name: "Sunny Island - Netzbezugszähler"
    unique_id: SiNetConsume
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 30581
    unit_of_measurement: "kWh"
  - name: "Sunny Island - Verbraucher"
    unique_id: SiConsumers
    data_type: int32 #S32
    input_type: holding
    slave: 3
    address: 30861
    unit_of_measurement: "W"
  - name: "Sunny Island - Status-SD-Card"
    unique_id: SiStateCard
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 40665
    unit_of_measurement: " " 
  - name: "Sunny Island - PowerIfOk"
    unique_id: SiPowerOK
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 30203
    unit_of_measurement: "W"
  - name: "Sunny Island - EnergyFeed"
    unique_id: SiFeedAC
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 30531
    unit_of_measurement: "kWh"
  - name: "Sunny Island - PV-EnergySum"
    unique_id: SiPVEnergySum
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 30587
    unit_of_measurement: "Wh"
  - name: "Sunny Island - EnergyConsumed"
    unique_id: SiEnergyConsumed
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 30593
    unit_of_measurement: "Wh"
  - name: "Sunny Island - ChargeCycles"
    unique_id: SiChargeCycles
    data_type: int32 #S32
    input_type: holding
    slave: 3
    address: 30857
    unit_of_measurement: " "
  - name: "Sunny Island - NetState"
    unique_id: SiFNetState
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 30883
    unit_of_measurement: " "
  - name: "Sunny Island - Temperatur"
    unique_id: SiTemp
    data_type: int32 #S32
    device_class: "temperature"
    unit_of_measurement: "°C"
    slave: 3
    address: 30953
    scale: 0.1
  - name: "Sunny Island - BatState"
    unique_id: SiBatState
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 30955
    unit_of_measurement: " "
  - name: "Sunny Island - BatUsageState"
    unique_id: SiBatUsageState
    data_type: int32 #U32
    input_type: holding
    slave: 3
    address: 31057
    unit_of_measurement: " "    
# SMA PV-Wechselrichter
- type: tcp
  host: 192.168.2.192
  port: 502
  name: "SMA STP20000"
  delay: 2
  message_wait_milliseconds: 60
  timeout: 5
  sensors:
  - name: SMA Power AC
    unique_id: SMAPowerAC
    device_class: power
    unit_of_measurement: W 
    slave: 3
    address: 30775
    data_type: uint32 #U32
  - name: SMA Tagesertrag
    unique_id: SMATagesertrag
    device_class: energy
    unit_of_measurement: Wh
    slave: 3
    address: 30517
    data_type: int64
  - name: SMA Total
    unique_id: SMATotal
    device_class: energy
    unit_of_measurement: Wh
    slave: 3
    address: 30513
    data_type: int64
  - name: SMA Volt
    unique_id: SMAVolt
    device_class: voltage
    unit_of_measurement: V
    slave: 3
    address: 30783
    data_type: int32
  - name: SMA Power L1 A 
    unique_id: SMAPowerL1A
    device_class: power
    unit_of_measurement: W
    slave: 3
    address: 30777
    data_type: uint32
  - name: SMA Power L2 A 
    unique_id: SMAPowerL2A
    device_class: power
    unit_of_measurement: W
    slave: 3
    address: 30779
    data_type: uint32
  - name: SMA Power L3 A 
    unique_id: SMAPowerL3A
    device_class: power
    unit_of_measurement: W
    slave: 3
    address: 30781
    data_type: uint32
  - name: SMA-STP_Temperatur"
    unique_id: StpTemp
    data_type: int32 #S32
    device_class: "temperature"
    unit_of_measurement: "°C"
    slave: 3
    address: 30953
    scale: 0.1
```
